/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class spanzuratoarea extends javax.swing.JFrame {

    double timeDisplay = 0;
    String cuvantulInLabel;
    boolean rezultatFinal = true;
    StringBuffer sb2 = new StringBuffer();
    Timer timer = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            timeDisplay += 0.1;

            sb2.append(String.valueOf(timeDisplay));
            if (timeDisplay < 10) {
                llTime.setText(sb2.substring(0, 3));
            } else {
                llTime.setText(sb2.substring(0, 4));
            }
            sb2.delete(0, sb2.length());

        }
    });

    private static String[] cuv = {"alfabet", "catalog", "magnific", "carte", "somnifer",
        "ciorap", "craciun", "farfurie", "javascript", "cocos", "laptop", "dell",
        "samsung", "certina", "minereu", "tastatura", "sange", "ceasornicar", "draperie", "ghiozdan", "Simba"}; //21

    private char[] stringAlesCharList = cuv[(int) Math.floor(Math.random() * (cuv.length))].toCharArray();
    private String[] cuvantAles = new String[stringAlesCharList.length];
    private String[] afisare;
    private int counter = 0;
    private boolean contine = false;

    private StringBuffer sb = new StringBuffer();

    private String indiciu;

    private void clear() {
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        labelTm.setVisible(false);
        yes.setVisible(false);
        labelCuvant.setText("Succes !");
        sb.delete(0, sb.length());
        sb2.delete(0, sb2.length());
        counter = 0;
        timeDisplay = 0;
        labelLitereIncercate.setText("");
        labelTm.setVisible(true);
        labelIndiciu.setVisible(false);
afisareIndiciu.setVisible(false);

    }

    public spanzuratoarea() {
        initComponents();
        clear();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labelLitera = new javax.swing.JTextField();
        bTry = new javax.swing.JButton();
        labelMesaj = new javax.swing.JLabel();
        labelCuvant = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelLitereIncercate = new javax.swing.JLabel();
        llTime = new javax.swing.JLabel();
        labelTm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yes = new javax.swing.JLabel();
        labelIndiciu = new javax.swing.JLabel();
        afisareIndiciu = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 30, 110, 32);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Litera:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 400, 80, 30);

        labelLitera.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelLitera.setForeground(new java.awt.Color(0, 0, 0));
        labelLitera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelLiteraActionPerformed(evt);
            }
        });
        labelLitera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelLiteraKeyPressed(evt);
            }
        });
        getContentPane().add(labelLitera);
        labelLitera.setBounds(120, 400, 110, 30);

        bTry.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bTry.setForeground(new java.awt.Color(0, 0, 0));
        bTry.setText("Ghiceste");
        bTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTryActionPerformed(evt);
            }
        });
        getContentPane().add(bTry);
        bTry.setBounds(240, 400, 130, 32);

        labelMesaj.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelMesaj.setForeground(new java.awt.Color(0, 0, 0));
        labelMesaj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelMesaj);
        labelMesaj.setBounds(30, 430, 460, 30);

        labelCuvant.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelCuvant.setForeground(new java.awt.Color(0, 0, 0));
        labelCuvant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCuvant.setText("Esti gata sa incepi?");
        getContentPane().add(labelCuvant);
        labelCuvant.setBounds(40, 360, 430, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Litere incercate:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 480, 170, 29);

        labelLitereIncercate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelLitereIncercate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelLitereIncercate);
        labelLitereIncercate.setBounds(200, 480, 450, 30);

        llTime.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        llTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(llTime);
        llTime.setBounds(670, 470, 70, 50);

        labelTm.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        labelTm.setForeground(new java.awt.Color(255, 255, 255));
        labelTm.setText("Timp:");
        getContentPane().add(labelTm);
        labelTm.setBounds(620, 470, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\p1.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 70, 150, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\p2.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 70, 160, 360);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/p3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 70, 160, 360);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/p4.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 70, 160, 370);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/p5.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 70, 150, 360);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/p6.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 70, 150, 360);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/p7.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 70, 130, 360);

        yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/yes2.png"))); // NOI18N
        getContentPane().add(yes);
        yes.setBounds(330, 140, 410, 380);

        labelIndiciu.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        labelIndiciu.setForeground(new java.awt.Color(255, 255, 255));
        labelIndiciu.setText("Indiciu:");
        getContentPane().add(labelIndiciu);
        labelIndiciu.setBounds(160, 140, 120, 30);

        afisareIndiciu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        afisareIndiciu.setForeground(new java.awt.Color(255, 255, 255));
        afisareIndiciu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(afisareIndiciu);
        afisareIndiciu.setBounds(40, 170, 300, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sp/dark-tree-and-sky.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 740, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
        labelMesaj.setText("");
        timer.start();

        int index = (int) Math.floor(Math.random() * (cuv.length));

        switch (index) {
            case 0:indiciu="Ce pot spune despre cuvant? are litere";break;
            case 1:indiciu="E ca o partitura muzicala";break;
            case 2:indiciu="De la bine in sus";break;
            case 3:indiciu="Cica pui burta pe ea";break;
            case 4:indiciu="zZz zZz zZz";break;
            case 5:indiciu="Niciodata nu-i gasesti perechea";break;
            case 6:indiciu="It's the most wonderful time of the year";break;
            case 7:indiciu="Doar n-o sa mananci de pe jos";break;
            case 8:indiciu="html,css,...";break;
            case 9:indiciu="Se scoala mereu primu dimineata";break;
            case 10:indiciu="ctrl+alt+del";break;
            case 11:indiciu="Marca de laptop";break;
            case 12:indiciu="S7 S8 S9";break;
            case 13:indiciu="Marca de ceas";break;
            case 14:indiciu="Sapi dupa el";break;
            case 15:indiciu="O folosesti acum";break;
            case 16:indiciu="coptura,beshici";break;
            case 17:indiciu="Meserie extrem de 'apreciata'";break;
            case 18:indiciu="O tragi cand te dor ochii";break;
            case 19:indiciu="Era mai greu ca tine la un moment dat";break;
            case 20:indiciu="leu";break;

        }
        afisareIndiciu.setText(indiciu);
labelIndiciu.setVisible(true);
afisareIndiciu.setVisible(true);
        char[] charCuvant = cuv[index].toCharArray();

        cuvantAles = new String[charCuvant.length];

        for (int i = 0; i < charCuvant.length; i++) {
            cuvantAles[i] = String.valueOf(charCuvant[i]);
        }

        afisare = new String[cuvantAles.length];
        for (int i = 0; i < cuvantAles.length; i++) {
            afisare[i] = " _ ";
        }
        cuvantulInLabel = Arrays.toString(afisare);
int lengthCuv=cuvantulInLabel.length();
cuvantulInLabel=cuvantulInLabel.substring(1,lengthCuv-1);
        labelCuvant.setText(cuvantulInLabel);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void actiune() {
        String litera = labelLitera.getText();
        for (int i = 0; i < cuvantAles.length; i++) {
            if (cuvantAles[i].equalsIgnoreCase(litera)) {
                afisare[i] = litera.toUpperCase();
                contine = true;
                labelMesaj.setText("Cuvantul contine litera " + labelLitera.getText().toUpperCase());

            }

            labelCuvant.setText(Arrays.toString(afisare));

        }
        if (!contine) {
            labelMesaj.setText("Cuvantul nu contine litera " + labelLitera.getText().toUpperCase());
            sb.append(" / " + litera);
            labelLitereIncercate.setText(sb.toString());
            counter++;
            switch (counter) {
                case 1:
                    jLabel1.setVisible(true);
                    break;
                case 2:
                    jLabel2.setVisible(true);
                    break;
                case 3:
                    jLabel3.setVisible(true);
                    break;
                case 4:
                    jLabel4.setVisible(true);
                    break;
                case 5:
                    jLabel5.setVisible(true);
                    break;
                case 6:
                    jLabel6.setVisible(true);
                    break;
                case 7:
                    jLabel7.setVisible(true);
                    break;

            }
        }
        contine = false;
        labelLitera.setText("");
        if (counter >= 7) {
            labelMesaj.setText("AI PIERDUT !");
            timeDisplay = 0;
            timer.stop();
        }
        if (Arrays.toString(cuvantAles).equalsIgnoreCase(Arrays.toString(afisare))) {
            labelMesaj.setText("AI CASTIGAT");
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            labelTm.setVisible(false);
            yes.setVisible(true);
            timer.stop();
        }

    }

    private void bTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTryActionPerformed
        actiune();

// TODO add your handling code here:
    }//GEN-LAST:event_bTryActionPerformed

    private void labelLiteraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelLiteraKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            actiune();
        }
    }//GEN-LAST:event_labelLiteraKeyPressed

    private void labelLiteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelLiteraActionPerformed

    }//GEN-LAST:event_labelLiteraActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spanzuratoarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spanzuratoarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spanzuratoarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spanzuratoarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                spanzuratoarea s = new spanzuratoarea();
                s.setVisible(true);
                s.setSize(760, 560);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afisareIndiciu;
    private javax.swing.JButton bTry;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCuvant;
    private javax.swing.JLabel labelIndiciu;
    private javax.swing.JTextField labelLitera;
    private javax.swing.JLabel labelLitereIncercate;
    private javax.swing.JLabel labelMesaj;
    private javax.swing.JLabel labelTm;
    private javax.swing.JLabel llTime;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
